// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-east-1",
    "aws_cognito_identity_pool_id": "us-east-1:06c8b002-c688-49bc-af52-e79bdc37037e",
    "aws_cognito_region": "us-east-1",
    "aws_user_pools_id": "us-east-1_49MYElDIG",
    "aws_user_pools_web_client_id": "jlttvagt1ilr4f2ahq0au2dvv",
    "oauth": {},
    "aws_dynamodb_all_tables_region": "us-east-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "triposts",
            "region": "us-east-1"
        },
        {
            "tableName": "commentsdynamo",
            "region": "us-east-1"
        }
    ],
    "aws_cloud_logic_custom": [
        {
            "name": "triapi",
            "endpoint": "https://v04piwioyl.execute-api.us-east-1.amazonaws.com/Prod",
            "region": "us-east-1"
        }
    ],
    "aws_content_delivery_bucket": "triportal-20180923210204--hostingbucket",
    "aws_content_delivery_bucket_region": "us-east-1",
    "aws_content_delivery_url": "http://triportal-20180923210204--hostingbucket.s3-website-us-east-1.amazonaws.com"
};


export default awsmobile;
